### PR TITLE
Added Jenkins name and description

### PR DESCRIPTION
**Pull request by animuk**

### CODE REVIEW

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
The tests will fail because your PR to the jenkinsfile-library repository was not merged yet. I suggest you to change the build to read from your forked repository temporarily until the PR is merged

**Comment by gastaldi** [comment]
You can find how to squash your commits into a single one in step 10 here: https://github.com/forge/core/blob/master/CONTRIBUTING.asciidoc

**Comment by gastaldi** [comment]
Also last but not least try to redact the commit message in this format: http://karma-runner.github.io/2.0/dev/git-commit-msg.html

**Comment by animuk** [comment]
Fixes #173 #177

**Comment by animuk** [comment]
[test]

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@animuk the changes introduced by your PR in the Jenkinsfile library may have broken the legacy code: https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/legacy-osio-addon/src/main/java/io/fabric8/forge/generator/pipeline/JenkinsPipelineLibrary.java 

Can you make sure that points that to a fixed tag?

**Comment by edewit** [comment]
[test]

**Pull request merged**
