### PR TITLE
Reordered the launch process, code push first then webhook creation

### PR DESCRIPTION
**Pull request by piyush1594**
Pushing code later may trigger a build and two builds are getting triggered, so first push code
then create webhook and we are already triggering build later.
Fixes https://github.com/openshiftio/openshift.io/issues/3742
Fixes https://github.com/openshiftio/openshift.io/issues/3252

### Checklist

- [x] I followed the contribution [guidelines](https://raw.githubusercontent.com/fabric8-launcher/launcher-backend/master/CONTRIBUTING.md).
- [x] I created an [issue](https://github.com/fabric8-launcher/launcher-backend/issues/new) and used it in the commit message.
  I linked the PR to OSIO issues.
- [x] I have built the project locally prior to submission with `mvn clean install`.
- [x] I kept a clean commit log (no unnecessary commits, no merge commits).
- [x] I am happy with my contribution.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @piyush1594 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by gastaldi** [comment]
@piyush1594 don't forget to change `OsioImportMissionControl#launch` as well

**Comment by piyush1594** [comment]
@gastaldi Addressed, but please not merge it for the time being

**Comment by gastaldi** [comment]
Looks good, can you change your commit message to what's specified in https://github.com/fabric8-launcher/launcher-backend/blob/master/COMMIT_MSG.md? Thanks!

**Comment by gastaldi** [comment]
@piyush1594 I added the `do not merge` label to this PR. Feel free to remove it when you need it merged

**Comment by piyush1594** [comment]
@gastaldi Thanks, will properly test it tomorrow with help of @ravsa and then do all the changes if required and commit message formatting

**Comment by gastaldi** [comment]
@piyush1594 almost forgot, you need to change the event order in https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioLaunchEndpoint.java#L57 and https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioImportEndpoint.java#L56 as well

**Comment by piyush1594** [comment]
@gastaldi Addressed the changes

**Comment by piyush1594** [comment]
@gastaldi I tested the full launch mission flow with the help of @ravsa and its working fine. I think we are good to merge this PR. I don't have rights to remove the `do not merge` label.

**Comment by gastaldi** [comment]
Thanks for the PR!

**Comment by piyush1594** [comment]
Just for tracking, this is in prod by https://github.com/openshiftio/saas-launchpad/pull/178

Thanks @gastaldi

**Pull request merged**
