### PR TITLE
feat(creator): Added Kotlin version of Creator

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by quintesse** [comment]
Btw, I'd definitely squash this PR while merging ;-)

**Comment by quintesse** [comment]
Hey! No force-pushing you said. ;-) You just threw several of my commits away.

**Comment by gastaldi** [comment]
Ah shit, I rebased with master and may have forgotten to pull first, sorry :(

**Comment by quintesse** [comment]
Luckily I noticed before I pulled so cherry-pick came to the rescue :-)

**Pull request merged**
