### PR TITLE
feat(git): Add possibility to use a 'secret' when creating a git hook

### LINKED ISSUE #59: GitService.createHook should support web hook secrets
The `GitService.createHook` method should be improved to accept a (nullable) secret to the created web hook

### PR DESCRIPTION
**Pull request by quintesse**
Where to find those in git apis:
- config key to add secret for github "secret":
https://developer.github.com/v3/repos/hooks/#create-a-hook
- url param to add secret for gitlab "token":
https://docs.gitlab.com/ee/api/projects.html#add-project-hook

Update tests in accordance.

Fixed version of #72, closes #59

### CODE REVIEW

**Comment by quintesse** [comment]
test this please

**Comment by quintesse** [comment]
@centos-ci retest this please

**Comment by gastaldi** [comment]
add to whitelist

**Comment by quintesse** [comment]
@centos-ci retest this please

**Pull request merged**
