### PR TITLE
fix(keycloak): handle errors in KeycloakIdentityProvider

### LINKED ISSUE #351: ProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.St...
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/3494/

```
JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper@30fe9cc; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
    at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:862)
...
(89 additional frame(s) were not displayed)

ProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper@30fe9cc; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
    at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:300)
    at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:196)
    at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:226)
    at io.fabric8.launcher.addon.MissionControl.lambda$getOpenShiftClusters$0(MissionControl.java:185)
    at io.fabric8.launcher.addon.MissionControl.perform(MissionControl.java:216)
...
(76 additional frame(s) were not displayed)

Error while returning openshift clusters
```

This was caused by your recent commit. Mind checking this out?

### PR DESCRIPTION
**Pull request by ia3andy**
Following previous behavior getIdentity/getIdentityAsync are supposed to catch and log exception then return empty. This was causing the error because the endpoint was failing on the first unconnected cluster.

Closes #351

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @ia3andy for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by ia3andy** [comment]
@quintesse I do agree with you on this point and I already thought the same. 

Though, this endpoint is called in many parts of the app and changing this behavior needs a lot of testing for success and failure. It will be much easier to change and test it when the old endpoints will be deleted. Let's create an issue for that for when the time comes. WDYT?

**Comment by quintesse** [comment]
Perfect, go ahead.

**Comment by ia3andy** [comment]
@quintesse -> https://github.com/fabric8-launcher/launcher-backend/issues/354

**Pull request merged**
