### PR TITLE
New `/catalog` endpoint and automatic `X-App` filtering

### PR DESCRIPTION
**Pull request by quintesse**

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @quintesse for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by gastaldi** [comment]
How about publishing in `/booster-catalog` instead of `/booster-catalog/catalog`?

**Comment by quintesse** [comment]
How do I edit the swagger.yaml file? By hand?? Then how do I check it's correct?

**Comment by quintesse** [comment]
> How about publishing in /booster-catalog instead of /booster-catalog/catalog?

Dunno, because it seems weird to me? We still have other endpoints like `/reindex` there as well.

**Comment by gastaldi** [comment]
IMHO that would be more appropriate (eg. To return the booster catalog you do a `GET /booster-catalog`) 

Any other action (like reindex) is already modeled as subpaths

**Comment by gastaldi** [comment]
I used https://editor.swagger.io/?url=https://forge.api.prod-preview.openshift.io/swagger.yaml to check it's correctness but I think there is an IDE plug-in for that

**Pull request merged**
