### PR TITLE
Ensure webhooks are created only after github push is complete

### PR DESCRIPTION
**Pull request by tinakurian**
### Why

Potential fix for: https://github.com/openshiftio/openshift.io/issues/3742

According to the following comment by @piyush-garg the builds might be triggered twice intermittently due to the createWebHooks(...) method being called prior to the pushToGitRepository(...) method completing: https://github.com/openshiftio/openshift.io/issues/3742#issuecomment-447838579

### Description

The solution implemented is a simple callback to listeners who are interested in knowing when the push has completed. Once the callback is called, the createWebHooks(...) method is invoked. 

Was tested to ensure that everything continues to work normally. However, unsure if this will fix the issue as it has been proven difficult to reproduce locally:
screenshot from 2018-12-19 14-02-03

Closes #3742
https://github.com/openshiftio/openshift.io/issues/3742

### Checklist

- [ ] I followed the contribution [guidelines](https://raw.githubusercontent.com/fabric8-launcher/launcher-backend/master/CONTRIBUTING.md).
- [ ] I created an [issue](https://github.com/fabric8-launcher/launcher-backend/issues/new) and used it in the commit message.
- [ ] I have built the project locally prior to submission with `mvn clean install`.
- [ ] I kept a clean commit log (no unnecessary commits, no merge commits).
- [ ] I am happy with my contribution.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @tinakurian for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by tinakurian** [comment]
> [ok-without-tests]

Thanks @piyush-garg i think it needs to be `/ok-without-tests` do you mind adding another comment?

**Comment by alien-ike** [comment]
Hey @piyush-garg! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by tinakurian** [comment]
@gastaldi It was to force a callback to be invoked when the push to github method completes. @piyush-garg was explaining that the push can take some time to finish and the webhooks call is intermittently made before the push is completed causing two builds to be triggered. See comment: https://github.com/openshiftio/openshift.io/issues/3742#issuecomment-447838579

**Comment by gastaldi** [comment]
@tinakurian I'm almost certain that this is already happening here, given that the crreateWebhook method is called after the pushToRepository method.

**Comment by tinakurian** [comment]
> @tinakurian I'm almost certain that this is already happening here, given that the crreateWebhook method is called after the pushToRepository method.

Yeah, i wasn't confident in this change. I think the issue maybe is more with the library we are using. Perhaps it spawns a thread somewhere when it executes the push and it doesn't wait for a return from the thread. However, I did have a peek at the library code and couldn't really verify whether this is what was happening...

**Comment by gastaldi** [comment]
The Push happens using jGit, but I believe that it returns immediately once it finishes execution, no threads involved.  Maybe something in GitHub?

**Comment by tinakurian** [comment]
> The Push happens using jGit, but I believe that it returns immediately once it finishes execution, no threads involved. Maybe something in GitHub?

@piyush-garg just mentioned an idea that may be more suitable - he was suggesting maybe checking that the code exists before we invoke the createWebHooks call? Would this be more reasonable?

@gastaldi is there another solution you had in mind? Or would this work?

**Comment by gastaldi** [comment]
@tinakurian what happens if you add a breakpoint after pushToRepository executes? Can you check if the sources are immediately available?

**Comment by tinakurian** [comment]
> @tinakurian what happens if you add a breakpoint after pushToRepository executes? Can you check if the sources are immediately available?

I can check, my guess would be that they are, except maybe in the case where two builds are triggered. I haven't been able to reproduce this issue locally... 

Do you think we could add logs to see what the source looks like when two builds are triggered in production?

**Comment by gastaldi** [comment]
@tinakurian sure, feel free to add some log statements there and I'll be happy to merge them ;)

**Comment by gastaldi** [comment]
What happens if you change `OSIOMissionControl` to the following order instead: 

1. Create Repository
2. Configure Webhooks
3. Push code

**Comment by gastaldi** [comment]
@piyush-garg considering that the webhook is meant to be triggered everytime a PUSH happens, why the following order wouldn't be more appropriate?

1. Create Repository
2. Create Webhooks
3. Push code

Maybe the events registered in the webhook need to be reviewed?

**Comment by piyush-garg** [comment]
@gastaldi @tinakurian 

That's should be the process I think,
1. Create Repository
2. Create Webhooks
3. Push code and build get triggered

But the current process is 
1. Create Repository
2. Push Code https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java#L74
3. Create webhook https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java#L77
4. Trigger build https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java#L83

I don't know the reason why the process is like this.

**Comment by gastaldi** [comment]
This could have been my mistake when migrating from the legacy codebase. 

@tinakurian mind closing this PR and opening a new one inverting the order to do the following and see what happens?

1. Create Repository
2. Create Webhooks
3. Push code

**Comment by tinakurian** [comment]
> This could have been my mistake when migrating from the legacy codebase.
> 
> @tinakurian mind closing this PR and opening a new one inverting the order to do the following and see what happens?
> 
> 1. Create Repository
> 2. Create Webhooks
> 3. Push code

Will do!

**Pull request closed without merging**
