### PR TITLE
chore(osio): remove blank booster and dependencies 

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @gastaldi for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by alien-ike** [comment]
Hey @gastaldi! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by bartoszmajsak** [comment]
(it seems hooks are dead)

**Comment by bartoszmajsak** [comment]
I suggest to put it on hold until we remove all the client code.

**Comment by joshuawilson** [comment]
fabric8-ui currently has the Blank in it.  
Why are you removing it?  
Are you removing it from the launcher-frontend?

**Comment by gastaldi** [comment]
>Why are you removing it?
Because it was decided as per @bartoszmajsak's email

>Are you removing it from the launcher-frontend?
Yes

**Comment by joshuawilson** [comment]
Doesn't fabric8-ui still get it's UI for the launcher from your launcher-frontend? If so, then when you remove it there, it will remove it for us too.

**Comment by gastaldi** [comment]
@joshuawilson you're talking about ngx-launcher, which yes, will be removed too. But I believe there are some changes needed in fabric8-ui where this component is included.

**Comment by joshuawilson** [comment]
I've created a story for the fabric8-ui work at https://openshift.io/openshiftio/Openshift_io/plan/detail/903
Please let me know when the launcher-ngx change is done and then we can follow up.

**Comment by gastaldi** [comment]
Depends on https://github.com/fabric8-ui/fabric8-ui/pull/3393

**Pull request merged**
