### PR TITLE
feat(health-check): Use Microprofile Health Check

### PR DESCRIPTION
**Pull request by gastaldi**
This replaces the trivial HealthCheckEndpoint

Health checks are used to probe the state of a computing node from another machine (i.e. kubernetes service controller) with the primary target being cloud infrastructure environments where automated processes maintain the state of computing nodes.
In this scenario, health checks are used to determine if a computing node needs to be discarded (terminated, shutdown) and eventually replaced by another (healthy) instance.
It’s not intended (although could be used) as a monitoring solution for human operators.

This allows implementations to return information that could decide whether this service is available or not.

Spec: https://github.com/eclipse/microprofile-health/
Article: https://developers.redhat.com/blog/2018/03/05/cloud-native-microprofile-config-healthcheck-openshift/

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @gastaldi for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by alien-ike** [comment]
Hey @gastaldi! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer, but not pull request creator for this command to take an effect.

**Comment by gastaldi** [comment]
Note that the build ran faster with this PR, probably because I removed HealthCheckEndpointIT

**Comment by ia3andy** [comment]
Good job removing code without loosing functionalities :)

**Pull request merged**
