### PR TITLE
Updated BCS to version 38

### PR DESCRIPTION
**Pull request by quintesse**

### CODE REVIEW

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-backend/commit/42ff404e60a43d4ac57e097b19aee8905be5e86c

**Comment by quintesse** [comment]
The idea was to merge this when the BCS was ready ;)

**Comment by quintesse** [comment]
And the other commit is missing the fix in the test it seems

**Comment by gastaldi** [comment]
Yeah, I wanted to percolate this change to production and release the booster-catalog. The fix in the test was  already pushed in https://github.com/fabric8-launcher/launcher-backend/commit/647f592518e081a1038d030fd7399cf35e559c74 (when I mentioned in [slack](https://obsidian-toaster.slack.com/archives/C33ABAG6T/p1527865868000177) )

**Comment by quintesse** [comment]
Ah ok, nice!

**Pull request closed without merging**
