### PR TITLE
fix(#92): updated Hoverfly to 0.10.0 & fixed test in GitHubServiceIT

### PR DESCRIPTION
**Pull request by MatousJobanek**
#### changes proposed in this PR:

* updated Hoverfly-java to 0.10.0
* fixed `GitHubServiceIT#throwExceptionOnDuplicateWebhook` test 
* replaced deprecated method `HoverflyConfig.configs()` with `HoverflyConfig.localConfigs()`

fixes: #92

### CODE REVIEW

**Comment by quintesse** [comment]
@centos-ci test this please

**Comment by quintesse** [comment]
@centos-ci ok to test , test this please

**Comment by gastaldi** [comment]
Add to whitelist

**Comment by bartoszmajsak** [comment]
[test]

**Comment by gastaldi** [comment]
LGTM. Mind rebasing this PR with the base branch before we merge it?

**Comment by MatousJobanek** [comment]
rebased @gastaldi

**Comment by gastaldi** [comment]
Thanks @MatousJobanek

**Pull request merged**
