### PR TITLE
Chore: Add Golang stack

### PR DESCRIPTION
**Pull request by jarifibrahim**
### Why
The Golang stack was missing. The Golang boosters cannot run with node/java che stacks.

### Description
This PR 
- Adds new Golang enum to CheStacks
- Updates CheStackDetector to check for golang stack

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jarifibrahim for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by jarifibrahim** [comment]
@gastaldi Please have a look at https://github.com/fabric8-launcher/launcher-backend/pull/648/commits/7d6dac429f7f09beef9ad460e5e39fa62d6d5821 . I've added a `main.go` and `package.json` file also. Let me know if you think we should change something else.

**Comment by gastaldi** [comment]
LGTM

**Comment by jarifibrahim** [comment]
@gastaldi The tests are failing and I don't understand why. Do you have any idea?

**Comment by gastaldi** [comment]
Yes, Because of https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions. I am still looking for a solution for this. I'll run the build locally meanwhile and merge after it

**Comment by gastaldi** [comment]
Thanks!

**Pull request merged**
